### ISSUE TITLE
Prettier deprecation warning: `jsxBracketSameLine` is deprecated

### ISSUE THREAD

**Issue by matbour** [csquare-ai/prettier-config#1]
With Prettier 2.4, `jsxBracketSameLine` is now [deprecated](https://prettier.io/blog/2021/09/09/2.4.0.html#replace-jsxbracketsameline-option-with-bracketsameline-option-11006httpsgithubcomprettierprettierpull11006-by-kurtztechhttpsgithubcomkurtztech).

We need to update our configuration accordingly.

**Comment by dimitri-bret** [comment]
@mathieu-bour  this is closed by 634e7c9 :)

**Comment by matbour** [comment]
Thanks @dimitri-bret, but we will wait to release the actual package before closing this issue.

**Comment by mkuysunov** [comment]
https://prettier.io/blog/2021/09/09/2.4.0.html#:~:text=This%20release%20renames%20the%20jsxBracketSameLine,such%20as%20class%20static%20blocks.
